services:
  frontend:
    container_name: 'nextjs'
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules

  backend:
    container_name: 'fastapi'
    build:
      context: ./backend
      dockerfile: Dockerfile

    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./backend
        target: /app

volumes:
  node_modules:

# 開発環境
# docker compose up

# 本番環境
# docker build --target prod .