services:
  frontend:
    container_name: 'nextjs'
    build:
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - node_modules:/app/node_modules

  backend:
    container_name: 'fastapi'
    build:
      context: ./backend
      dockerfile: ./backend/Dockerfile

    ports:
      - 8000:8000
    volumes:
      - type: bind
        source: ./backend
        target: /app

volumes:
  node_modules:
